CREATE TABLE production_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    job_number VARCHAR(50) NOT NULL,
    product_name VARCHAR(200) NOT NULL,

    ordered_quantity INTEGER NOT NULL,
    produced_quantity INTEGER NOT NULL DEFAULT 0,
    waste_quantity INTEGER NOT NULL DEFAULT 0,

    status VARCHAR(30) NOT NULL,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT uk_production_jobs_job_number
        UNIQUE (job_number),

    CONSTRAINT chk_production_jobs_ordered_quantity
        CHECK (ordered_quantity > 0),

    CONSTRAINT chk_production_jobs_produced_quantity
        CHECK (produced_quantity >= 0),

    CONSTRAINT chk_production_jobs_waste_quantity
        CHECK (waste_quantity >= 0),

    CONSTRAINT chk_production_jobs_status
        CHECK (
            status IN (
                'CREATED',
                'PRODUCTION_READY',
                'PRINTING',
                'PRINTED',
                'REWINDING',
                'COMPLETED'
            )
        )
);