CREATE TABLE production_job_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    production_job_id BIGINT NOT NULL,

    from_status VARCHAR(30),
    to_status VARCHAR(30) NOT NULL,

    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT fk_production_job_events_job
        FOREIGN KEY (production_job_id)
        REFERENCES production_jobs(id),

    CONSTRAINT chk_production_job_events_from_status
        CHECK (
            from_status IS NULL
            OR from_status IN (
                'CREATED',
                'PRODUCTION_READY',
                'PRINTING',
                'PRINTED',
                'REWINDING',
                'COMPLETED'
            )
        ),

    CONSTRAINT chk_production_job_events_to_status
        CHECK (
            to_status IN (
                'CREATED',
                'PRODUCTION_READY',
                'PRINTING',
                'PRINTED',
                'REWINDING',
                'COMPLETED'
            )
        )
);

CREATE INDEX idx_production_job_events_job_and_time
    ON production_job_events(production_job_id, occurred_at);